name: Check for updates

on:
  schedule:
    - cron: "23 1 * * *"
  workflow_dispatch:
    inputs:
      dry-run:
        default: true
        description: 'Perform a dry run'
        required: false

jobs:
  check-versions:
    runs-on: ubuntu-latest
    env:
      TAILWIND_API: "https://api.github.com/repos/tailwindlabs/tailwindcss/releases/latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest Tailwind version
        run: |
          echo "TAILWIND_VERSION=$(curl -s $TAILWIND_API | jq -r '.tag_name' | cut -c 2-)" >> $GITHUB_ENV

      - name: Get latest Preflight version
        run: |
          echo "PREFLIGHT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Run update check if Tailwind version is greater than Preflight version
        run: |
          if [[ ${{ env.TAILWIND_VERSION }} > ${{ env.PREFLIGHT_VERSION }} ]]; then
            echo "update=true" >> $GITHUB_OUTPUT
          else
            echo "update=false" >> $GITHUB_OUTPUT
          fi
        id: check-update
  
      - name: Run update
        if: ${{ steps.check-update.outputs.update == 'true' }}
        uses: ./.github/workflows/update.yaml
        with:
          tailwind-version: ${{ env.TAILWIND_VERSION }}
          preflight-version: ${{ env.PREFLIGHT_VERSION }}
          dry-run: ${{ github.event.inputs.dry-run }}
          force: ${{ github.event.inputs.force }}