name: Update Preflight

on:
  workflow_call:
    inputs:
      tailwind-version:
        description: 'Tailwind CSS version'
      preflight-version:
        description: 'Preflight version'
      dry-run:
        description: 'Perform a dry run'
  workflow_dispatch:
    inputs:
      tailwind-version:
        description: 'Tailwind CSS version'
        required: true
      preflight-version:
        description: 'Preflight version'
        required: true
      dry-run:
        default: true
        description: 'Perform a dry run'
        required: false

jobs:
  update-preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Download preflight.css from Tailwind release
        run: |
          curl -sL -o preflight.css "https://cdn.jsdelivr.net/npm/tailwindcss@${{ inputs.tailwind-version }}/src/css/preflight.css"
          echo "Successfully downloaded & replaced preflight.css"

      - name: Update package.json version
        run: |
          npm version --no-git-tag-version ${{ inputs.tailwind-version }}
          echo "Successfully updated package.json version"

      - name: Publish package
        if: ${{ inputs.dry-run }} == false
        run: |
          npm publish
          echo "Successfully published package"

      - name: Stage files
        if: ${{ inputs.dry-run }} == false
        run: |
          git add preflight.css package.json
          echo "Successfully staged files"

      - name: Configure git
        if: ${{ inputs.dry-run }} == false
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-actions@github.com"
          echo "Successfully configured git"

      - name: Commit changes
        if: ${{ inputs.dry-run }} == false
        run: |
          git commit -m "Updated Preflight to ${{ inputs.tailwind-version }}"
          echo "Successfully committed changes"

      - name: Push changes
        if: ${{ inputs.dry-run }} == false
        run: |
          git push
          echo "Successfully pushed changes"