name: Update Preflight

on:
  schedule:
    - cron: '23 1 * * *' # Runs at 01:23 UTC every day

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Check latest Tailwind CSS version
        id: tailwind-version
        run: |
          TAILWIND_VERSION=$(curl -s 'https://api.github.com/repos/tailwindlabs/tailwindcss/releases/latest' | jq -r '.tag_name' | cut -c 2-)
          echo "::set-output name=tailwind_version::$TAILWIND_VERSION"

      - name: Read current Preflight version
        id: preflight-version
        run: |
          PREFLIGHT_VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=preflight_version::$PREFLIGHT_VERSION"

      - name: Update Preflight
        if: steps.tailwind-version.outputs.tailwind_version > steps.preflight-version.outputs.preflight_version
        run: |
          curl -s "https://cdn.jsdelivr.net/npm/tailwindcss@${TAILWIND_VERSION}/src/css/preflight.css" --output preflight.css
          npm version "${TAILWIND_VERSION}"
          npm run publish
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add preflight.css package.json
          git commit -m "Update Preflight to ${TAILWIND_VERSION}"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}